# Application Config
base.url=https://www.saucedemo.com
browser=chrome
implicit.wait=10
explicit.wait=15
page.load.timeout=30

# Test Credentials
valid.username=standard_user
valid.password=secret_sauce
invalid.username=wrong_user
invalid.password=wrong_pass

# Reports
report.path=reports/TestReport.html
screenshot.path=reports/screenshots/
